### PR TITLE
4.0.0

### PR DESCRIPTION
**Pull request by curbengh**
This release is mainly to support ES2018+ features.

### CODE REVIEW

**Comment by curbengh** [comment]
Just tested with hexo-generator-feed, with the following error:
```
'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead  node/no-deprecated-api
```

[old URL API](https://nodejs.org/api/url.html#url_legacy_url_api) (i.e. `url.parse` & `url.resolve`) is required for Node 8 compatibility, Node 8 doesn't support the [new URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api).

Edit: https://github.com/hexojs/eslint-config-hexo/pull/19

**Comment by tomap** [comment]
I merged #19 
And I would like to also include #20 
(I'm unsure about the purpose of test.js)

**Comment by curbengh** [comment]
Merged #20

**Comment by curbengh** [comment]
My fork is corrupted.

**Pull request closed without merging**
